version: '3.8'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    pull_policy: never # this means that the images are not pulled from dockerhub
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always # this means that the container will be restarted if it crashes
    env_file: .env

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    pull_policy: never
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    env_file: .env
    secrets:
      - db_root_password
      - db_password

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    pull_policy: never
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always
    env_file: .env
    depends_on:
      - mariadb
    secrets:
      - db_password
      - credentials

networks: # the network is used to connect the containers
  inception:
    driver: bridge # the bridge driver is used to connect the containers, diver: bridge means that the containers will be connected to the bridge network
    # bridge network is the default network driver for Docker

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pmolzer/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/pmolzer/data/wordpress

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt # Verified: ensure this path is correct relative to compose file
  db_password:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt